Repository ayansiddiqui007/hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#5 #4 commit 1
  hack.py
Labels: good first issue, hacktoberfest, hacktoberfest2022

#8 #3
  tt.py
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest2022

#6 #2 hacked
  game.py
Labels: bug, documentation, good first issue, hacktoberfest, hacktoberfest2022

#10 Added a new file under the issue #9
  CoffeHouse.py
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#11 Added code for is palindrome
  is_palindrome.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#19 #18
  oo.py
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#13 2
  is_palindrome.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#17 #16
  README.md
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#15 #14
  oo.py
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#20 reactjs
  Hactober fest commit accepted
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#22 #21
  CoffeHouse.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#27 22
  README.md
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#28 #26
  CoffeHouse.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#30 Create bgRemover.py
  bgRemover.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#31 Add files via upload
  sudoku through pygame.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#34 Create euclidGCD.py
  euclidGCD.py
Labels: documentation, help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#33 A sample code to download and check the version of openCV used
  CVSAMPLE.ipynb
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#32 Added program for weather notifications in desktop
  .gitignore
  weather_notifications_desktop.py
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#35 Laravel 2022 commit hacktoberfest
  Laravel
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#38 User
  User-function
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#37 MM
  Message model laravel
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#36 Update hacktober
  Update database
Labels: help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT
