Repository ayansiddiqui007/hacktoberfest2022, pull requests merged in 2023-10, with the labels that each got.

#42 Create quizGame.py
  Rajat Rai Python GUI Games/quizGame.py
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#40 Create TicTacToe.py
  TicTacToe.py
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#24 2
  Hactober fest commit accepted
Labels: good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT

#52 Update User-function
  User-function
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#48 Update Laravel
  Laravel
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#49 Update CVSAMPLE.ipynb
  CVSAMPLE.ipynb
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#51 Update sudoku through pygame.py
  sudoku through pygame.py
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#50 Update game.py
  game.py
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#61 Create bmicalculator.html
  bmicalculator.html
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#62 Insertion sort in c and Longest prefix in python
  Insertion_Sort.c
  longest_prefix.py
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#64 Create Palindrome.c
  Palindrome.c
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#65 added fizzbuzz program
  fizz.cpp
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#66 Update Hactober fest commit accepted
  Hactober fest commit accepted
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#67 Update is_palindrome.py
  is_palindrome.py
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#68 Update hack.py
  hack.py
Labels: enhancement, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#69 Update weather_notifications_desktop.py
  weather_notifications_desktop.py
Labels: help wanted, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#70 added a game of madlibs in python
  madlibsgame.py
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#71 Ritwik2
  linkedlist.py
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023

#72 Create passwordgenerator.c
  passwordgenerator.c
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST-ACCEPT, hacktoberfest 2023
